[build]
  publish = "dist"
  command = "npm run export"

# https://www.issaonline.com/blog/index.cfm/2021/how-to-maximize-fitness-with-energy-systems-training
[[redirects]]
  from = "/blog/index.cfm/2021"
  to = "/posts"
  status = 301
  force = false
  query = {path = ":path"} #  apply this rule for /old-path?path=example
  conditions = {Language = ["en","es"], Country = ["US"]}